# Generated by Django 4.1.2 on 2022-10-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(default='Porro quaerat quisquam non ut ut dolor etincidunt. Amet eius eius dolor. Quisquam dolorem voluptatem amet quaerat aliquam. Aliquam velit modi ut non. Velit amet porro est.', max_length=600, null=True),
        ),
    ]
