# Generated by Django 4.1.2 on 2022-10-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(default='Ut sit dolor non dolor voluptatem velit. Etincidunt ut tempora etincidunt sed etincidunt quisquam. Quaerat neque amet ut aliquam eius. Quisquam etincidunt ut ipsum quiquia velit sit consectetur. Non etincidunt sit porro labore eius. Neque numquam dolor ut quiquia. Adipisci sed etincidunt magnam aliquam magnam.', max_length=600, null=True),
        ),
    ]
