# Generated by Django 4.1.2 on 2022-10-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0007_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Quisquam aliquam dolor dolore amet neque dolor. Aliquam modi quiquia dolor quaerat est quisquam velit. Dolorem labore modi aliquam. Est porro modi dolorem non. Numquam quiquia labore sit tempora consectetur dolorem. Ipsum dolorem dolorem tempora. Dolore etincidunt porro etincidunt. Amet labore eius labore. Ipsum eius ipsum est magnam magnam sit non.', max_length=600, null=True),
        ),
    ]
