# Generated by Django 4.1.2 on 2022-10-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0008_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Numquam porro ut quiquia porro amet ut. Dolore est amet aliquam. Ipsum magnam adipisci non. Numquam quaerat velit etincidunt dolore quiquia. Quiquia consectetur sed voluptatem porro. Sit labore quisquam consectetur sit amet. Adipisci amet velit aliquam modi. Dolore modi amet dolorem magnam dolore. Quaerat etincidunt dolore neque modi.', max_length=600, null=True),
        ),
    ]
