# Generated by Django 4.1.2 on 2022-10-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0009_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Ut est consectetur quiquia ipsum ut dolore aliquam. Quisquam labore voluptatem sed labore numquam non. Dolor quiquia sed eius numquam numquam consectetur. Dolorem neque sed voluptatem numquam. Amet sed quaerat etincidunt dolorem quaerat quaerat amet. Magnam dolorem magnam eius consectetur magnam. Tempora adipisci ut quisquam sit sit magnam. Tempora est magnam porro. Numquam dolor magnam amet quaerat labore. Modi adipisci dolor consectetur.', max_length=600, null=True),
        ),
    ]
