# Generated by Django 4.1.2 on 2022-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0010_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Magnam velit tempora sit dolorem quisquam. Porro consectetur dolore dolorem aliquam amet. Amet eius etincidunt quiquia. Dolorem velit magnam numquam. Est tempora etincidunt eius ut velit adipisci sed. Quiquia neque aliquam neque amet aliquam quaerat. Quisquam non aliquam neque modi quaerat aliquam voluptatem.', max_length=600, null=True),
        ),
    ]
