# Generated by Django 4.1.2 on 2022-10-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0011_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Labore etincidunt modi etincidunt voluptatem aliquam adipisci sed. Numquam dolorem sit dolorem sed aliquam. Tempora ut ipsum ipsum. Consectetur adipisci numquam non. Eius neque est est modi.', max_length=600, null=True),
        ),
    ]
