# Generated by Django 4.1.2 on 2022-10-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0012_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Voluptatem numquam magnam aliquam numquam. Etincidunt ipsum magnam voluptatem est quisquam magnam non. Velit voluptatem adipisci tempora adipisci. Aliquam velit dolore etincidunt sed numquam. Eius consectetur quaerat quisquam ut. Consectetur modi quaerat aliquam. Quiquia modi adipisci consectetur dolor quiquia numquam magnam. Quaerat etincidunt labore sed dolore est. Quisquam aliquam ut eius quisquam eius est consectetur. Consectetur quisquam aliquam dolore tempora labore voluptatem dolor.', max_length=600, null=True),
        ),
    ]
