# Generated by Django 4.1.2 on 2022-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0014_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Quiquia modi ipsum modi sit porro magnam. Sed quisquam sed magnam. Amet velit etincidunt labore. Non sit sed ut porro. Dolorem dolore sit velit labore neque. Dolor voluptatem neque eius non quiquia tempora. Aliquam ipsum amet dolorem. Magnam adipisci voluptatem neque eius neque ut sed.', max_length=600, null=True),
        ),
    ]
