# Generated by Django 4.1.2 on 2022-10-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0015_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Tempora neque porro quaerat tempora aliquam adipisci voluptatem. Labore quiquia ipsum labore neque. Numquam dolorem numquam tempora. Dolor quiquia voluptatem voluptatem labore. Neque modi sit quisquam dolorem dolor dolor quisquam. Aliquam magnam dolore voluptatem quaerat. Adipisci numquam eius non dolorem est labore etincidunt.', max_length=600, null=True),
        ),
    ]
