# Generated by Django 4.1.2 on 2022-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0016_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Etincidunt quisquam non numquam numquam aliquam. Sit quaerat eius velit amet sed ipsum dolorem. Voluptatem ut est etincidunt adipisci quisquam eius. Porro neque tempora dolor dolor. Tempora etincidunt velit tempora. Sed dolor aliquam velit magnam sit adipisci dolorem. Quiquia quaerat dolore velit eius sed magnam est. Quisquam sed amet tempora quisquam. Ipsum dolore sed dolor ut numquam.', max_length=600, null=True),
        ),
    ]
